# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    UserProfile = apps.get_model("users", "UserProfile")
    db_alias = schema_editor.connection.alias

    for profile in UserProfile.objects.using(db_alias).filter(uuid=None):
        profile.uuid = uuid.uuid4()
        profile.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_null_uuid_to_user_profile'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),

        migrations.AlterField(
            model_name='userprofile',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
