# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_populate_user_profile_uuid_make_non_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='enable_ical',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_cipher_preferences',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_expiry',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_product_updates',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_short_id_usage',
            field=models.BooleanField(default=True),
        ),
    ]
