# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 17:31
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blacklist', '0003_create_new_custom_permission'),
        ('users', '0006_add_more_settings_to_user_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchResultForKeysByEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('key_fingerprints', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), size=None)),
                ('email_address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='latest_search_by_email', to='blacklist.EmailAddress')),
            ],
        ),
    ]
