# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-22 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_allow_blank_search_rsult'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyOwnershipProof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pgp_key', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner_proof', to='keys.PGPKey')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pgp_key_ownership_proofs', to='users.UserProfile')),
            ],
        ),
    ]
