# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-09 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_keyownershipproof'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='receive_occasional_feedback_requests',
            field=models.BooleanField(default=False, help_text='Receive occasional emails asking for feedback on ideas.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='welcome_email_sent_datetime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
