# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-18 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0002_add_key_algo_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uid',
            name='uid_string',
            field=models.CharField(db_index=True, max_length=500),
        ),
    ]
