# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-18 15:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0003_add_db_index_to_uid_string'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uid',
            name='key',
        ),
        migrations.DeleteModel(
            name='UID',
        ),
    ]
