# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-22 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0005_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pgpkey',
            name='key_algorithm',
            field=models.CharField(blank=True, choices=[('DSA', 'DSA (1)'), ('RSA-SIGN', 'RSA Sign-only (3)'), ('ELGAMAL', 'ELGAMAL (16)'), ('RSA', 'RSA (17)'), ('ECC', 'ECC (18)'), ('ECDSA', 'ECDSA (19)')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pgpkey',
            name='key_length_bits',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
