# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-22 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0006_make_algorithm_and_bits_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uid',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uids_set', to='keys.PGPKey'),
        ),
    ]
