# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-22 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import expirybot.apps.keys.models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0007_rename_uids_related_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pgpkey',
            name='fingerprint',
            field=models.CharField(help_text='The 40-character key fingerprint without spaces.', max_length=40, primary_key=True, serialize=False, validators=[expirybot.apps.keys.models.validate_fingerprint]),
        ),
    ]
