# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-27 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0008_add_validators_to_fingerprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgpkey',
            name='revoked',
            field=models.NullBooleanField(default=None),
        ),
    ]
