# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-05 21:27
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import expirybot.apps.keys.models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0009_pgpkey_revoked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subkey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('long_id', models.CharField(max_length=16)),
                ('key_algorithm', models.CharField(choices=[('DSA', 'DSA (1)'), ('RSA-SIGN', 'RSA Sign-only (3)'), ('ELGAMAL', 'ELGAMAL (16)'), ('RSA', 'RSA (17)'), ('ECC', 'ECC (18)'), ('ECDSA', 'ECDSA (19)')], max_length=10)),
                ('key_length_bits', models.PositiveIntegerField(blank=True, null=True)),
                ('creation_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('revoked', models.NullBooleanField(default=None)),
                ('capabilities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('C', 'certifying other keys'), ('S', 'signing data'), ('E', 'encrypting data'), ('A', 'authenticating')], max_length=1), blank=True, size=None)),
            ],
            bases=(models.Model, expirybot.apps.keys.models.FriendlyCapabilitiesMixin, expirybot.apps.keys.models.ExpiryCalculationMixin),
        ),
        migrations.AddField(
            model_name='subkey',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subkeys_set', to='keys.PGPKey'),
        ),
    ]
