# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-05 21:35
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0010_add_subkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pgpkey',
            name='creation_datetime',
        ),
        migrations.RemoveField(
            model_name='pgpkey',
            name='expiry_datetime',
        ),
        migrations.AddField(
            model_name='pgpkey',
            name='creation_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='pgpkey',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
