# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-05 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0012_add_capabilities_to_pgp_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pgpkey',
            name='revoked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subkey',
            name='revoked',
            field=models.BooleanField(default=False),
        ),
    ]
