# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-09 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0013_make_revoked_non_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pgpkey',
            name='key_algorithm',
            field=models.CharField(blank=True, choices=[('DSA', 'DSA (1)'), ('RSA-SIGN', 'RSA Sign-only (3)'), ('ELGAMAL', 'ELGAMAL (16)'), ('RSA', 'RSA (17)'), ('ECC', 'ECC (18)'), ('ECDSA', 'ECDSA (19)'), ('', 'Unknown')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='subkey',
            name='key_algorithm',
            field=models.CharField(blank=True, choices=[('DSA', 'DSA (1)'), ('RSA-SIGN', 'RSA Sign-only (3)'), ('ELGAMAL', 'ELGAMAL (16)'), ('RSA', 'RSA (17)'), ('ECC', 'ECC (18)'), ('ECDSA', 'ECDSA (19)'), ('', 'Unknown')], max_length=10),
        ),
    ]
