# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-19 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0015_set_null_false_for_key_algorithm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pgpkey',
            name='key_algorithm',
            field=models.CharField(blank=True, choices=[('', 'Unknown'), ('RSA', 'RSA (1)'), ('RSA-ENCRYPT', 'RSA Encrypt-only (2)'), ('RSA-SIGN', 'RSA Sign-only (3)'), ('ELGAMAL', 'ELGAMAL (Encrypt-only) (16)'), ('DSA', 'DSA (17)'), ('ECC', 'Elliptic curve - ECDH encrypt / ECDSA sign (18/19)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subkey',
            name='key_algorithm',
            field=models.CharField(blank=True, choices=[('', 'Unknown'), ('RSA', 'RSA (1)'), ('RSA-ENCRYPT', 'RSA Encrypt-only (2)'), ('RSA-SIGN', 'RSA Sign-only (3)'), ('ELGAMAL', 'ELGAMAL (Encrypt-only) (16)'), ('DSA', 'DSA (17)'), ('ECC', 'Elliptic curve - ECDH encrypt / ECDSA sign (18/19)')], max_length=10),
        ),
    ]
