# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-26 17:30
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import expirybot.apps.keys.models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0017_add_ecc_curve_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgpkey',
            name='alerts_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list, encoder=expirybot.apps.keys.models.CustomJSONEncoder),
        ),
        migrations.AddField(
            model_name='subkey',
            name='alerts_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list, encoder=expirybot.apps.keys.models.CustomJSONEncoder),
        ),
    ]
