# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-04 09:52
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import expirybot.apps.keys.models.custom_json_encoder
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0018_add_alerts_json_to_keys'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyTestResult',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('test_results', django.contrib.postgres.fields.jsonb.JSONField(default=dict, encoder=expirybot.apps.keys.models.custom_json_encoder.CustomJSONEncoder)),
            ],
        ),
    ]
