# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-19 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0019_keytestresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokenKey',
            fields=[
                ('fingerprint', models.CharField(help_text='The 40-character key fingerprint without spaces.', max_length=40, primary_key=True, serialize=False)),
                ('next_retry_sync', models.DateTimeField()),
            ],
        ),
    ]
