# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-24 10:37
from __future__ import unicode_literals

from django.db import migrations, models
import expirybot.apps.keys.models.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0021_brokenkey_error_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyUpdate',
            fields=[
                ('sks_hash', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(db_index=True)),
                ('fingerprint', models.CharField(blank=True, db_index=True, help_text='The 40-character key fingerprint without spaces.', max_length=40, null=True)),
            ],
            bases=(models.Model, expirybot.apps.keys.models.mixins.FingerprintFormatMixin),
        ),
    ]
