# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-24 10:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0022_add_key_update_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyupdate',
            options={'permissions': (('add_key_update', 'Can create key KeyUpdate records.'),)},
        ),
    ]
