#!/bin/sh -eu


THIS_SCRIPT=$0
THIS_DIR=$(dirname ${THIS_SCRIPT})

GPG=/usr/bin/gpg2
FIREJAIL=/usr/bin/firejail

FAKE_HOME='/tmp/gpg-fake-home'

export GNUPGHOME="${FAKE_HOME}/.gnupg"
/bin/mkdir -p "${GNUPGHOME}"
/bin/chmod 700 "${GNUPGHOME}"

/bin/cp "${THIS_DIR}/skel/gpg.conf" "${GNUPGHOME}/gpg.conf"


exec $GPG \
  --batch \
  --no-tty \
  "$@"
