#!/bin/sh -eu

# Given a filename to an ASCII-armored PGP key, return the output of
# gpg --list-keys for the key contained within


THIS_SCRIPT=$(/bin/readlink -f $0)
THIS_DIR=$(/usr/bin/dirname ${THIS_SCRIPT})

ASCII_KEY_FILENAME=$1

GPG="/usr/bin/gpg2 --batch --no-tty"

TMP_BASEDIR="/tmp/gpg_dump_key"
/bin/mkdir -p ${TMP_BASEDIR}

TEMP_DIR=$(/bin/mktemp -p ${TMP_BASEDIR} -d --suffix .gpghome)
export GNUPGHOME=${TEMP_DIR}

/bin/cp ${THIS_DIR}/../skel/* "${GNUPGHOME}/"
/bin/chmod -R 700 "${GNUPGHOME}"

$GPG --fast-import "${ASCII_KEY_FILENAME}"

# NOTE: keep in sync with script/delete_old_test_results
LIST_KEYS_FN=$(/bin/mktemp -p ${TMP_BASEDIR} --suffix .list-keys.txt)
LIST_PACKETS_FN=$(/bin/mktemp -p ${TMP_BASEDIR} --suffix .list-packets.txt)

$GPG --list-keys > ${LIST_KEYS_FN}
$GPG --export-options export-minimal --export | $GPG --list-packets > ${LIST_PACKETS_FN}

echo "LIST_KEYS: ${LIST_KEYS_FN}"
echo "LIST_PACKETS: ${LIST_PACKETS_FN}"

/usr/bin/gpgconf --kill gpg-agent

/bin/rm -rf ${TEMP_DIR}
