#!/bin/sh

THIS_SCRIPT=$0
REPO_DIR=$(dirname ${THIS_SCRIPT})/..

setup_django_environment() {
  export DJANGO_SETTINGS_MODULE=expirybot.settings.production
}

load_secrets_environment_variables() {
  . ${REPO_DIR}/secrets.sh
}


setup_virtualenv() {
  REQUIREMENTS_HASH=$(sha1sum ${REPO_DIR}/requirements.txt | cut '-d ' -f1)

  VENV_DIR="${REPO_DIR}/venv/${REQUIREMENTS_HASH}"

  if [ ! -f "${VENV_DIR}/bin/python" ]; then
    virtualenv -p $(which python3) "${VENV_DIR}"
  fi

  set +u
  . "${VENV_DIR}/bin/activate"
  set -u

  pip install -r "${REPO_DIR}/requirements.txt"
}

install_requirements() {
  pip install -r ${REPO_DIR}/requirements.txt
}

setup_django_environment
load_secrets_environment_variables
setup_virtualenv
install_requirements
