#!/bin/sh -eux

THIS_SCRIPT=$0
REPO_DIR=$(dirname ${THIS_SCRIPT})/..

. ${REPO_DIR}/script/_setup_environment

build_css() {
  cd ${REPO_DIR}
  make css
  cd -
}

collect_static_files() {
  ${REPO_DIR}/manage.py collectstatic --no-input --clear
}

migrate_database() {
  ${REPO_DIR}/manage.py migrate --no-input
}


build_css
collect_static_files
migrate_database

# Replace current script with gunicorn
exec gunicorn expirybot.wsgi -b 127.0.0.1:8011
