#!/bin/sh -eux

THIS_SCRIPT=$0
REPO_DIR=$(dirname ${THIS_SCRIPT})/..

. ${REPO_DIR}/script/_setup_environment


# TODO: this, or only localhost, for example
# --net=none

exec firejail \
  --caps.drop=all \
  ${REPO_DIR}/manage.py sync_keys
