# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-19 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventLatestOccurrence',
            fields=[
                ('event_slug', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('last_occurred_datetime', models.DateTimeField()),
            ],
        ),
    ]
