# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-11 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blacklist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAddress',
            fields=[
                ('email_address', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unsubscribe_datetime', models.DateTimeField(blank=True, default=None, null=True)),
                ('complain_datetime', models.DateTimeField(blank=True, default=None, null=True)),
                ('last_bounce_datetime', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='BlacklistedEmailAddress',
        ),
    ]
