# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-11 22:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blacklist', '0002_change_blacklisted_email_to_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailaddress',
            options={'permissions': (('make_unsubscribe_links', 'Can create unsubscribe links for email addresses.'),)},
        ),
    ]
