# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-17 22:56
from __future__ import unicode_literals

from django.contrib.postgres.operations import CITextExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blacklist', '0003_create_new_custom_permission'),
    ]

    operations = [
        CITextExtension(),
    ]
