# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-17 23:45
from __future__ import unicode_literals

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blacklist', '0004_enable_case_insensitive_text_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaddress',
            name='email_address',
            field=django.contrib.postgres.fields.citext.CIEmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
